name: Claude Code Review

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  claude-review:
    uses: your-org/github-workflows-central/.github/workflows/claude-reusable.yml@main
    with:
      trigger_phrase: "@claude"
      assignee_trigger: "Yagami360"
      japanese_output: true
      max_turns: 3
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
