name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-review:
    uses: Yagami360/claude-code-custom-actions/.github/workflows/claude.yml@master
    with:
      trigger_phrase: "@claude"
      # assignee_trigger: "Yagami360"
      japanese_output: true
      max_turns: 1
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
